---
title: "modeling"
author: "Carolyn Jane Anderson"
date: "June 4, 2018"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
#import data
n <- c("belief","gen","obs_major","obs_school","obs_name","obs_loc","obs_w","utterance","major", "school","name","loc","w","participant","prob")
pairs <- read.csv('~/dissertation/modeling/motionmod/learning_test.tsv',header=FALSE,comment.char = "#",col.names=n,sep='\t')
```

```{r}
pairs$prob <- as.numeric(as.character(pairs$prob))
```

```{r}
ggplot(data=pairs,mapping=aes(x=gen,y=prob,shape=w,color=w)) + geom_point() + facet_wrap(belief~participant) + ylab("Posterior probability") + xlab("Name") + geom_path() + labs(color="Name",shape="Name")
#ggsave("test.png",width=12, height=5)
```

```{r}
ggplot(data=subset(pairs,belief=="German_State_Daniel_outdoor"),mapping=aes(x=gen,y=prob,shape=name,color=name)) + geom_point() + facet_wrap(~participant) + ylab("Posterior probability") + xlab("Name") + geom_path() + labs(color="Person",shape="Person")
ggsave("img/learn_daniel.png")
```

```{r}
ggplot(data=subset(pairs,obs_w==belief),mapping=aes(x=utterance,fill=obs_name)) + geom_bar()+ labs(fill="Observation",x="Utterance",y="Gen") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggsave("img/learn_utts.png")
```

```{r}
ggplot(data=subset(pairs,obs_w==belief),mapping=aes(y=utterance,x=gen,color=obs_w, group=obs_w,linetype=obs_w)) +geom_point() + geom_line()+ labs(fill="Observation",x="Generation",y="Utterance") + theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggsave("img/learn_utts.png")
```
