---
title: "modeling"
author: "Carolyn Jane Anderson"
date: "June 4, 2018"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
source("../../../coding/wellesley_palette.R")
```

```{r}
#import data
get.number <- function(x) {
  if(x=="N A S"){return("W1")}
  else {
  if(x=="A A S"){return("W2")}
  else{
  if(x=="A N L"){return("W3")}
  else{
  if(x=="A A L"){return("W4")}
  else{
  if(x=="N N T"){return("W5")}
    else{
  if(x=="A A T"){return("W6")}
      else{
  if(x=="N A T"){return("W7")}
        else{
  if(x=="A N T"){return("W8")}
          else{
  if(x=="E E T"){return("W9")}
          else{cat("\nNOT FOUND")}}}}}}}}}
}

get.label <- function(x) {
  if(x=="N A S"){return("Listener")}
  else {
  if(x=="A A S"){return("None")}
  else{
  if(x=="A N L"){return("Speaker")}
  else{
  if(x=="A A L"){return("None")}
  else{
  if(x=="N N T"){return("Both")}
    else{
  if(x=="A A T"){return("None")}
      else{
  if(x=="N A T"){return("Listener")}
        else{
  if(x=="A N T"){return("Speaker")}
          else{cat("\nNOT FOUND")}}}}}}}}
}

n <- c("go","cost","utterance","perspective","locSam","locLucy","moveLucy", "moveSam","moveThelma","probability")
```

```{r}
#datanm = "lit_speaker"
#datanm = "prag_speaker_early"
datanm = "prag_speaker"
#datanm = "prag_speaker_double"
datad = paste0('img/',datanm,'_')
```

```{r}
prob_pairs = TRUE
if(datanm == "lit_speaker"){
  nogop_n = 'speaker_aug_nogop.csv'
  gop_n = 'speaker_aug_gop.csv'
  prob_n = 'speaker_aug_prob.csv'
}
if(datanm == "prag_speaker"){
  nogop_n = 'pragspeaker_nogop.csv'
  gop_n = 'pragspeaker_gop.csv'
  prob_n = 'pragspeaker_prob.csv'
}
if(datanm == "prag_speaker_early"){
  nogop_n = 'pragspeaker_early_nogop.csv'
  gop_n = 'pragspeaker_early_gop.csv'
  prob_n = 'pragspeaker_early_prob.csv'
}
if(datanm == "prag_speaker_double"){
  nogop_n = 'pragspeaker_double_nogop.csv'
  gop_n = 'pragspeaker_double_gop.csv'
  prob_n = 'pragspeaker_double_prob.csv'
}
```

```{r}
prob.pairs <- read.csv(prob_n,header=FALSE,col.names=n,comment.char = "#")
nogop.pairs <- read.csv(nogop_n,header=FALSE,col.names=n,comment.char = "#")
gop.pairs <- read.csv(gop_n,header=FALSE,col.names=n,comment.char = "#")
pairs <- rbind(rbind(nogop.pairs,prob.pairs),gop.pairs)
pairs <- pairs %>% mutate(go.is.p = ifelse(grepl('prob',go,fixed=TRUE),
                                           'prob',
                                           ifelse(grepl('nogop',go,fixed=TRUE),
                                                  'nogop',
                                                  'gop')))
pairs$go.is.p <- factor(pairs$go.is.p, levels=c('gop','nogop','prob'))
```

```{r}
pairs$probability <- as.numeric(as.character(pairs$probability))
pairs <- pairs %>% rowwise() %>% mutate(mover=ifelse(moveSam=='true',"S",ifelse(moveLucy=='true',"L","T")))

pairs <- pairs %>% rowwise() %>% mutate(world=paste("L in",substr(toString(locLucy),1,1),"\n S in",substr(toString(locSam),1,1)))
```

```{r}
pairs <- pairs %>% rowwise() %>% mutate(world1=paste(substr(toString(locLucy),1,1),substr(toString(locSam),1,1),substr(toString(mover),1,1)))
pairs <- pairs %>% rowwise() %>% mutate(worldNum = get.number(world1),
                                        Condition = get.label(world1))
pairs <- pairs %>% rowwise() %>% mutate(world=paste(world,"\n",worldNum))
```

```{r}
pairs$go.is.p <- as.factor(pairs$go.is.p)
p_marginals <- pairs %>% group_by(go.is.p,world1,utterance,cost) %>% mutate(marg.prob = sum(probability))
u_marginals <- pairs %>% group_by(go.is.p,world,perspective,cost) %>% mutate(marg.prob = sum(probability))
summarize(subset(p_marginals,grepl("Thelma",utterance,fixed=TRUE)), pmarg = unique(marg.prob))
```

```{r}
pairs <- pairs %>% mutate(perspective.and.utterance = paste(as.character(perspective),paste("\n",as.character(utterance))))
facet_labs <- c(Lucy = "Perspective holder = Lucy", Sam = "Perspective holder = Sam")
facet_go_labs <- c(gop="Perspectival go",nogop="Plain go",prob="Lex. uncertain go")
```

```{r}
moveThelma <- subset(pairs, as.character(utterance)=='Thelma is coming to Northampton' | as.character(utterance)=='Thelma is going to Northampton' | as.character(utterance)=='Thelma is walking to Northampton')
moveSam <- subset(pairs, moveSam=="true")
ggplot(data=moveThelma,mapping=aes(x=world,y=probability,size=cost,shape=utterance,color=perspective)) + geom_point() + facet_wrap(moveThelma$go.is.p) + scale_color_wellesley(palette = "main")
ggsave(paste0(datad,"Tmove.pdf"),width=12, height=5)
```

```{r}
c1_moveThelma <- subset(moveThelma,cost==1)
ggplot(data=c1_moveThelma,mapping=aes(x=world,y=probability,size=cost,shape=utterance,color=perspective)) + geom_point() + facet_wrap(c1_moveThelma$go.is.p) + scale_color_wellesley(palette = "main")
ggsave(paste0(datad,"Tmove_cost1.pdf"),width=12, height=5)
```
```{r}
c0_moveThelma <- subset(moveThelma,cost==0)
ggplot(data=c0_moveThelma,mapping=aes(x=world,y=probability,size=cost,shape=utterance,color=perspective)) + geom_point(position = position_dodge(width=0.99)) + facet_wrap(~go.is.p,labeller=as_labeller(facet_go_labs)) + scale_color_wellesley(palette = "main")
ggsave(paste0(datad,"Tmove_cost0.pdf"),width=12, height=5)
```

```{r}
c0_moveThelma_noprob <- subset(c0_moveThelma,go.is.p!='prob')
ggplot(data=c0_moveThelma_noprob,mapping=aes(x=world,y=probability,size=cost,shape=utterance,color=utterance)) + geom_point() + facet_wrap(go.is.p~perspective,labeller=labeller(perspective = facet_labs,go.is.p=facet_go_labs)) + labs(shape="Utterance",color="Utterance") + guides(size=FALSE) + scale_color_wellesley(palette = "main")
ggsave(paste0(datad,"Tmove_cost0_noprob.pdf"),width=12, height=5)
```

```{r}
pmarg_moveThelma <- subset(p_marginals, as.character(utterance)=='Thelma is coming to Northampton' | as.character(utterance)=='Thelma is going to Northampton' | as.character(utterance)=='Thelma is walking to Northampton' | as.character(utterance)=='NULL')
pmarg_moveSam <- subset(p_marginals, moveSam=="true")
ggplot(data=pmarg_moveThelma,mapping=aes(x=world,y=marg.prob,size=cost,color=utterance,shape=utterance)) + geom_point() + facet_wrap(~go.is.p,labeller=as_labeller(facet_go_labs)) + labs(size="Cost",color="Utterance",shape="Utterance")
ggsave(paste0(datad,"pmarg_Tmove.pdf"),width=12, height=5)
```

```{r}
pmarg_moveThelma_noprob <- subset(pmarg_moveThelma,go.is.p!='prob')
ggplot(data=pmarg_moveThelma_noprob,mapping=aes(x=world,y=marg.prob,size=cost,color=utterance,shape=utterance)) + geom_point() + facet_wrap(~go.is.p,labeller=as_labeller(facet_go_labs)) + labs(size="Cost",color="Utterance",shape="Utterance") 
ggsave(paste0(datad,"pmarg_Tmove_noprob.pdf"),width=12, height=5)
```

```{r}

f <- function(x) {
  r <- quantile(x, probs = c(0, 0, 0.5, 1, 1))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}

f2 <- function(x) {
  r <- quantile(x, probs = c(0, 0.5, 1))
  names(r) <- c("ymin", "y", "ymax")
  r
}

pmarg_moveSam_nogop <- subset(subset(pmarg_moveSam,go.is.p=='nogop'),cost < 1.1)
pmarg_moveThelma_nogop <- subset(subset(pmarg_moveThelma,go.is.p=='nogop'),cost < 1.1)
pmarg_moveThelma_nogop$Condition <- factor(pmarg_moveThelma_nogop$Condition,levels = c("Both", "Speaker", "Listener", "None"))

ggplot(data=pmarg_moveThelma_nogop,aes(x=utterance,y=marg.prob,color=utterance)) + stat_summary(fun.data = f2, geom="crossbar") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none")
ggsave(paste0(datad,"pmarg_Tmove_nogop.pdf"),height=3,width=12)

ggplot(data=subset(pmarg_moveThelma_nogop,cost==0|cost==1|cost==0.5),aes(x=utterance,y=marg.prob,fill=cost,group=cost)) + geom_col(position="dodge") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none",text=element_text(size=14))
ggsave(paste0(datad,"pmarg_Tmove_nogop_new.pdf"),height=3,width=12)

ggplot(data=subset(pmarg_moveSam_nogop,cost==0|cost==1|cost==0.5),aes(x=utterance,y=marg.prob,fill=cost,group=cost)) + geom_col(position="dodge") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("I am coming to Northampton" = "Come", "I am going to Northampton" = "Go", "I am walking to Northampton" = "Walk")) + theme(legend.position="none",text=element_text(size=14))
ggsave(paste0(datad,"pmarg_Smove_nogop_new.pdf"),height=3,width=12)
```

```{r}
sm <- pmarg_moveSam_nogop %>% mutate(Condition = paste0("Speaker Moving ",Condition))
list_none <- rbind(pmarg_moveThelma_nogop,sm)

list_none <- list_none %>% mutate(verb = ifelse(grepl("com",utterance),
                                                "Come",
                                                ifelse(grepl("go",utterance),"Go","Walk")))

ggplot(data=subset(list_none,(cost==0|cost==1|cost==0.5)&(grepl("List",Condition)|grepl("Moving None",Condition))),aes(x=verb,y=marg.prob,fill=cost,group=cost)) + geom_col(position="dodge") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("I am coming to Northampton" = "Come", "I am going to Northampton" = "Go", "I am walking to Northampton" = "Walk", "Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none",text=element_text(size=14))
ggsave(paste0(datad,"pmarg_SmoveTmove_nogop_new.pdf"),height=3,width=12)
```

```{r}
pmarg_moveThelma_gop <- subset(subset(pmarg_moveThelma,go.is.p=='gop'),cost < 1.1)
pmarg_moveThelma_gop$Condition <- factor(pmarg_moveThelma_gop$Condition,levels = c("Both", "Speaker", "Listener", "None"))

ggplot(data=pmarg_moveThelma_gop,aes(x=utterance,y=marg.prob,color=utterance)) + stat_summary(fun.data = f2, geom="crossbar") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none")
ggsave(paste0(datad,"pmarg_Tmove_gop.pdf"),height=3,width=12)

ggplot(data=subset(pmarg_moveThelma_gop,cost==0|cost==1|cost==0.5),aes(x=utterance,y=marg.prob,fill=cost,group=cost)) + geom_col(position="dodge") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none",text=element_text(size=14))
ggsave(paste0(datad,"pmarg_Tmove_gop_new.pdf"),height=3,width=12)
```

```{r}
umarg_moveThelma <- subset(u_marginals, as.character(utterance)=='Thelma is coming to Northampton' | as.character(utterance)=='Thelma is going to Northampton' | as.character(utterance)=='Thelma is walking to Northampton' | as.character(utterance)=='NULL')
ggplot(data=umarg_moveThelma,mapping=aes(x=utterance,y=marg.prob,color=cost,shape=perspective)) + geom_point() + facet_wrap(umarg_moveThelma$go.is.p)+ theme(axis.text.x = element_text(angle = 90)) + scale_color_wellesley(palette = "grad",discrete=FALSE)
ggsave(paste0(datad,"speak_umarg_nogopTmove.pdf"),width=12, height=5)
```

```{r}
umarg_moveThelma_c0 <- subset(umarg_moveThelma,cost==0)
ggplot(data=umarg_moveThelma_c0,mapping=aes(x=perspective,y=marg.prob,color=utterance,shape=utterance)) + geom_point() + facet_wrap(~go.is.p)+ theme(axis.text.x = element_text(angle = 90)) + scale_color_wellesley(palette = "main")
ggsave(paste0(datad,"speak_umarg_nogopTmove_c0.pdf"),width=12, height=5)
```
```{r}
pmarg_c05_moveThelma <- subset(pmarg_moveThelma,cost==0.5)
ggplot(data=pmarg_moveThelma,mapping=aes(x=world,y=marg.prob,color=cost,shape=utterance)) + geom_point() + facet_wrap(pmarg_moveThelma$go.is.p) + scale_color_wellesley(palette = "grad", discrete=FALSE)
ggsave(paste0(datad,"speak_pmarg_Tmove.pdf"),width=12, height=5)
ggplot(data=pmarg_c05_moveThelma,mapping=aes(x=world,y=marg.prob,color=utterance,shape=utterance)) + geom_point() + facet_wrap(pmarg_c05_moveThelma$go.is.p) + scale_color_wellesley(palette = "main")
ggsave(paste0(datad,"speak_c05_pmarg_Tmove.pdf"),width=12, height=5)
```

