---
title: "modeling"
author: "Carolyn Jane Anderson"
date: "June 4, 2018"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
#import data
get.number <- function(x) {
  if(x=="N A S"){return("W1")}
  else {
  if(x=="A A S"){return("W2")}
  else{
  if(x=="A N L"){return("W3")}
  else{
  if(x=="A A L"){return("W4")}
  else{
  if(x=="N N T"){return("W5")}
    else{
  if(x=="A A T"){return("W6")}
      else{
  if(x=="N A T"){return("W7")}
        else{
  if(x=="A N T"){return("W8")}
          else{
  if(x=="E E T"){return("W9")}
          else{cat("\nNOT FOUND")}}}}}}}}}
}

get.label <- function(x) {
  if(x=="N A S"){return("Listener")}
  else {
  if(x=="A A S"){return("None")}
  else{
  if(x=="A N L"){return("Speaker")}
  else{
  if(x=="A A L"){return("None")}
  else{
  if(x=="N N T"){return("Both")}
    else{
  if(x=="A A T"){return("None")}
      else{
  if(x=="N A T"){return("Listener")}
        else{
  if(x=="A N T"){return("Speaker")}
          else{cat("\nNOT FOUND")}}}}}}}}
}


n <- c("go","cost","utterance","perspective","locSam","locLucy","moveLucy", "moveSam","moveThelma","probability")
```

```{r}
datanm = "speaker_basic"
#datanm = "speaker_basic_simple"
#datanm = "speaker_sampled_pcost"
#datanm = "speaker_nonu_w"
#datanm = "speaker_nonu_apart_w"
#datanm = "speaker_speaker_bias"
#datanm = "speaker_listener_cost"
#datanm = "speaker_sample_wp"
#datanm = "speaker_speaker_default"
datad = paste0('img/',datanm,'_')
```

```{r}
prob_pairs = TRUE
if(datanm == "speaker_basic"){
  nogop_n = 'speaker_aug_nogop.csv'
  gop_n = 'speaker_aug_gop.csv'
  prob_n = 'speaker_aug_prob.csv'
}
if(datanm == "speaker_basic_simple"){
  nogop_n = 'speaker_simple_nogop.csv'
  gop_n = 'speaker_simple_gop.csv'
  prob_n = 'speaker_simple_prob.csv'
}
if(datanm == "speaker_sampled_pcost"){
  nogop_n = 'speaker_ucost_aug_nogop.csv'
  gop_n = 'speaker_ucost_aug_gop.csv'
  prob_n = 'speaker_ucost_aug_prob.csv'
}
if(datanm == "speaker_nonu_w"){
  nogop_n = 'speak_nonu_aug_nogop.csv'
  gop_n = 'speak_nonu_aug_gop.csv'
  prob_n = 'speak_nonu_aug_prob.csv'
}
if(datanm == "speaker_nonu_apart_w"){
  nogop_n = 'speak_nonu_apart_nogop.csv'
  gop_n = 'speak_nonu_apart_gop.csv'
  prob_n = 'speak_nonu_apart_prob.csv'
}
if(datanm == "speaker_speaker_bias"){
  nogop_n = 'irr_speaker_nogop.csv'
  gop_n = 'irr_speaker_gop.csv'
  prob_n = 'irr_speaker_prob.csv'
}
if(datanm == "speaker_sample_wp"){
  nogop_n = 'speaker_sample_wp_nogop.csv'
  gop_n = 'speaker_sample_wp_gop.csv'
  prob_n = 'speaker_sample_wp_prob.csv'
}
if(datanm == "speaker_listener_cost"){
  nogop_n = 'speaker_lcost_nogop.csv'
  gop_n = 'speaker_lcost_gop.csv'
  prob_n = 'speaker_lcost_prob.csv'
}
if(datanm == "speaker_listener_cost"){
  nogop_n = 'speaker_lcost_nogop.csv'
  gop_n = 'speaker_lcost_gop.csv'
  prob_n = 'speaker_lcost_prob.csv'
}
if(datanm == "speaker_speaker_default"){
  nogop_n = 'speaker_default_speaker_nogop.csv'
  gop_n = 'speaker_default_speaker_gop.csv'
  prob_n = 'speaker_default_speaker_prob.csv'
}
```

```{r}
prob.pairs <- read.csv(prob_n,header=FALSE,col.names=n,comment.char = "#",stringsAsFactors=TRUE)
nogop.pairs <- read.csv(nogop_n,header=FALSE,col.names=n,comment.char = "#",stringsAsFactors=TRUE)
gop.pairs <- read.csv(gop_n,header=FALSE,col.names=n,comment.char = "#",stringsAsFactors=TRUE)
pairs <- rbind(rbind(nogop.pairs,prob.pairs),gop.pairs)
pairs <- pairs %>% mutate(go.is.p = ifelse(grepl('prob',go,fixed=TRUE),
                                           'prob',
                                           ifelse(grepl('nogop',go,fixed=TRUE),
                                                  'nogop',
                                                  'gop')))
pairs$go.is.p <- factor(pairs$go.is.p, levels=c('gop','nogop','prob'))
```

```{r}
pairs$probability <- as.numeric(as.character(pairs$probability))
pairs <- pairs %>% rowwise() %>% mutate(mover=ifelse(moveSam=='true',"S",ifelse(moveLucy=='true',"L","T")))

pairs <- pairs %>% rowwise() %>% mutate(world=paste("L in",substr(toString(locLucy),1,1),"\n S in",substr(toString(locSam),1,1)))
```

```{r}
pairs <- pairs %>% rowwise() %>% mutate(world1=paste(substr(toString(locLucy),1,1),substr(toString(locSam),1,1),substr(toString(mover),1,1)))
pairs <- pairs %>% rowwise() %>% mutate(worldNum = get.number(world1),
                                        Condition = get.label(world1))
pairs <- pairs %>% rowwise() %>% mutate(world=paste(world,"\n",worldNum))
```

```{r}
pairs$go.is.p <- as.factor(pairs$go.is.p)
p_marginals <- pairs %>% group_by(go.is.p,world1,utterance,cost) %>% mutate(marg.prob = sum(probability))
u_marginals <- pairs %>% group_by(go.is.p,world,perspective,cost) %>% mutate(marg.prob = sum(probability))
summarize(subset(p_marginals,grepl("Thelma",utterance,fixed=TRUE)), pmarg = unique(marg.prob))
```

```{r}
pairs <- pairs %>% mutate(perspective.and.utterance = paste(as.character(perspective),paste("\n",as.character(utterance))))
facet_labs <- c(Lucy = "Perspective holder = Lucy", Sam = "Perspective holder = Sam")
facet_go_labs <- c(gop="Perspectival go",nogop="Plain go",prob="Lex. uncertain go")
```

```{r}
moveThelma <- subset(pairs, as.character(utterance)=='Thelma is coming to Northampton' | as.character(utterance)=='Thelma is going to Northampton' | as.character(utterance)=='Thelma is walking to Northampton')
moveThelma.nogop <- subset(moveThelma, go.is.p=='nogop')
ggplot(data=moveThelma,mapping=aes(x=Condition,y=probability,size=cost,shape=utterance,color=perspective)) + geom_point() + facet_wrap(moveThelma$go.is.p) + ylim(0,1) 
ggsave(paste0(datad,"Tmove.pdf"),width=12, height=5)
```

```{r}
c1_moveThelma <- subset(moveThelma,cost==1)
ggplot(data=c1_moveThelma,mapping=aes(x=Condition,y=probability,size=cost,shape=utterance,color=perspective)) + geom_point() + facet_wrap(c1_moveThelma$go.is.p) + ylim(0,1) 
ggsave(paste0(datad,"Tmove_cost1.pdf"),width=12, height=5)
```
```{r}
c0_moveThelma <- subset(moveThelma,cost==0)
ggplot(data=c0_moveThelma,mapping=aes(x=world,y=probability,size=cost,shape=utterance,color=perspective)) + geom_point(position = position_dodge(width=0.99)) + facet_wrap(~go.is.p,labeller=as_labeller(facet_go_labs)) + ylim(0,1) 
ggsave(paste0(datad,"Tmove_cost0.pdf"),width=12, height=5)
```

```{r}
c0_moveThelma_noprob <- subset(c0_moveThelma,go.is.p!='prob')
ggplot(data=c0_moveThelma_noprob,mapping=aes(x=world,y=probability,size=cost,shape=utterance,color=utterance)) + geom_point() + facet_wrap(go.is.p~perspective,labeller=labeller(perspective = facet_labs,go.is.p=facet_go_labs)) + labs(shape="Utterance",color="Utterance") + guides(size=FALSE) + ylim(0,1) 
ggsave(paste0(datad,"Tmove_cost0_noprob.pdf"),width=12, height=5)
```

```{r}
pmarg_moveThelma <- subset(p_marginals, as.character(utterance)=='Thelma is coming to Northampton' | as.character(utterance)=='Thelma is going to Northampton' | as.character(utterance)=='Thelma is walking to Northampton' | as.character(utterance)=='NULL')
ggplot(data=pmarg_moveThelma,mapping=aes(x=Condition,y=marg.prob,size=cost,color=utterance,shape=utterance)) + geom_point() + facet_wrap(~go.is.p,labeller=as_labeller(facet_go_labs)) + labs(size="Cost",color="Utterance",shape="Utterance") + ylim(0,1) 
ggsave(paste0(datad,"pmarg_Tmove.pdf"),width=12, height=5)
```

```{r}
f <- function(x) {
  r <- quantile(x, probs = c(0, 0, 0.5, 1, 1))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}

f2 <- function(x) {
  r <- quantile(x, probs = c(0, 0.5, 1))
  names(r) <- c("ymin", "y", "ymax")
  r
}

pmarg_moveThelma_nogop <- subset(subset(pmarg_moveThelma,go.is.p=='nogop'),cost < 1.1)
pmarg_moveThelma_nogop$Condition <- factor(pmarg_moveThelma_nogop$Condition,levels = c("Both", "Speaker", "Listener", "None"))

ggplot(data=pmarg_moveThelma_nogop,aes(x=utterance,y=marg.prob,color=utterance)) + stat_summary(fun.data = f2, geom="crossbar") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none")
ggsave(paste0(datad,"pmarg_Tmove_nogop.pdf"),height=3,width=12)

ggplot(data=subset(pmarg_moveThelma_nogop,cost==0|cost==1|cost==0.5),aes(x=utterance,y=marg.prob,fill=cost,group=cost)) + geom_col(position="dodge") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none",text=element_text(size=14))
ggsave(paste0(datad,"pmarg_Tmove_nogop_new.pdf"),height=3,width=12)
```

```{r}
pmarg_moveThelma_prob <- subset(subset(pmarg_moveThelma,go.is.p=='prob'),cost < 1.1)
pmarg_moveThelma_prob$Condition <- factor(pmarg_moveThelma_prob$Condition,levels = c("Both", "Speaker", "Listener", "None"))

ggplot(data=subset(pmarg_moveThelma_prob,cost==0|cost==1|cost==0.5),aes(x=utterance,y=marg.prob,fill=cost,group=cost)) + geom_col(position="dodge") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none",text=element_text(size=14))
ggsave(paste0(datad,"pmarg_Tmove_prob_new.pdf"),height=3,width=12)
```

```{r}
pmarg_moveThelma_gop <- subset(subset(pmarg_moveThelma,go.is.p=='gop'),cost < 1.1)
pmarg_moveThelma_gop$Condition <- factor(pmarg_moveThelma_gop$Condition,levels = c("Both", "Speaker", "Listener", "None"))

ggplot(data=pmarg_moveThelma_gop,aes(x=utterance,y=marg.prob,color=utterance)) + stat_summary(fun.data = f2, geom="crossbar") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none")
ggsave(paste0(datad,"pmarg_Tmove_gop.pdf"),height=3,width=12)

pmarg_moveThelma_prob <- subset(subset(pmarg_moveThelma,go.is.p=='prob'),cost < 1.1)
pmarg_moveThelma_prob$Condition <- factor(pmarg_moveThelma_prob$Condition,levels = c("Both", "Speaker", "Listener", "None"))

ggplot(data=pmarg_moveThelma_prob,aes(x=utterance,y=marg.prob,color=utterance)) + stat_summary(fun.data = f2, geom="crossbar") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none")
ggsave(paste0(datad,"pmarg_Tmove_prob.pdf"),height=3,width=12)

ggplot(data=subset(pmarg_moveThelma_gop,cost==0|cost==1|cost==0.5),aes(x=utterance,y=marg.prob,fill=cost,group=cost)) + geom_col(position="dodge") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none",text=element_text(size=14))
ggsave(paste0(datad,"pmarg_Tmove_gop_new.pdf"),height=3,width=12)
```

```{r}
ggplot(data=subset(pmarg_moveThelma_gop,cost==0|cost==1|cost==0.5),aes(x=utterance,y=marg.prob,fill=cost,group=cost)) + geom_col(position="dodge") + facet_wrap(~Condition, nrow = 2) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none",text=element_text(size=28)) + scale_fill_gradient(low = "#00ADB1",
  high = "#2C2551")
ggsave(paste0(datad,"pmarg_Tmove_gop_slides.pdf"),height=7,width=12)
```
```{r}
ggplot(data=subset(pmarg_moveThelma_gop,cost==0|cost==1|cost==0.5),aes(x=utterance,y=marg.prob,fill=cost,group=cost)) + geom_col(position="dodge") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none",text=element_text(size=17)) + scale_fill_gradient(low = "#00ADB1",
  high = "#2C2551")
ggsave(paste0(datad,"pmarg_Tmove_gop_slide2s.pdf"),height=3,width=12)
```

```{r}
ggplot(data=pmarg_moveThelma_nogop,aes(x=utterance,y=marg.prob,color=utterance)) + stat_summary(fun.data = f2, geom="crossbar") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none")
ggsave(paste0(datad,"pmarg_Tmove_nogop2.pdf"),height=3,width=12)

ggplot(data=pmarg_moveThelma_gop,aes(x=utterance,y=marg.prob,color=utterance)) + stat_summary(fun.data = f2, geom="crossbar") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("Marginal probability: p(u|w)") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none")
ggsave(paste0(datad,"pmarg_Tmove_gop2.pdf"),height=3,width=12)

ggplot(data=pmarg_moveThelma_prob,aes(x=utterance,y=marg.prob,color=utterance)) + stat_summary(fun.data = f2, geom="crossbar") + facet_wrap(~Condition, nrow = 1) + ylim(0,1) + ylab("") + scale_x_discrete(name ="Utterance", labels=c("Thelma is coming to Northampton" = "Come", "Thelma is going to Northampton" = "Go", "Thelma is walking to Northampton" = "Walk")) + theme(legend.position="none")
ggsave(paste0(datad,"pmarg_Tmove_prob2.pdf"),height=3,width=12)
```

```{r}
umarg_moveThelma <- subset(u_marginals, as.character(utterance)=='Thelma is coming to Northampton' | as.character(utterance)=='Thelma is going to Northampton' | as.character(utterance)=='Thelma is walking to Northampton' | as.character(utterance)=='NULL')
ggplot(data=umarg_moveThelma,mapping=aes(x=utterance,y=marg.prob,color=cost,shape=perspective)) + geom_point() + facet_wrap(umarg_moveThelma$go.is.p)+ theme(axis.text.x = element_text(angle = 90)) + ylim(0,1) 
ggsave(paste0(datad,"speak_umarg_nogopTmove.pdf"),width=12, height=5)
```

```{r}
umarg_moveThelma_c0 <- subset(umarg_moveThelma,cost==0)
ggplot(data=umarg_moveThelma_c0,mapping=aes(x=perspective,y=marg.prob,color=utterance,shape=utterance)) + geom_point() + facet_wrap(~go.is.p)+ theme(axis.text.x = element_text(angle = 90)) + ylim(0,1) 
ggsave(paste0(datad,"speak_umarg_nogopTmove_c0.pdf"),width=12, height=5)
```
```{r}
pmarg_c05_moveThelma <- subset(pmarg_moveThelma,cost==0.5)
ggplot(data=pmarg_moveThelma,mapping=aes(x=world,y=marg.prob,color=cost,shape=utterance)) + geom_point() + facet_wrap(pmarg_moveThelma$go.is.p)  + ylim(0,1)
ggsave(paste0(datad,"speak_pmarg_Tmove.pdf"),width=12, height=5)
ggplot(data=pmarg_c05_moveThelma,mapping=aes(x=world,y=marg.prob,color=utterance,shape=utterance)) + geom_point() + facet_wrap(pmarg_c05_moveThelma$go.is.p)  + ylim(0,1)
ggsave(paste0(datad,"speak_c05_pmarg_Tmove.pdf"),width=12, height=5)
```